services:
  - type: web
    name: burger-house-api
    runtime: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: burger-house-db
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      - key: FRONTEND_URL
        sync: false
      - key: GITHUB_PAGES_URL
        sync: false

databases:
  - name: burger-house-db
    plan: free
